---
dependency:
  name: galaxy
  requirements_file: requirements.yml
  options:
    ignore-certs: True
    ignore-errors: True
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/.yamllint
platforms:
  - name: ubuntu-16.04
    image: geerlingguy/docker-ubuntu1604-ansible:testing
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    verbose: true
    s: true
  lint:
    name: flake8
